### ISSUE TITLE
App icon not shown

### ISSUE THREAD

**Issue by drbarto** [magrinj/react-native-app-store-review#12]
Hi, first of all thanks for the great plugin!

When I trigger the rating dialog in a debug build, the app icon does not show up -- instead the default "no icon" icon of Xcode is used (just as in your screenshot). I was wondering whether this is expected behavior or a bug in my setup? 

As you wrote in the README, the popup cannot be tested in a Testflight build, so I'd have to release a new version in order to evaluate whether the icon is being shown correctly. If the issue persists, all my users would see the invalid icon -- not good. So maybe you can clarify this for me.

(P.S. I already posted a more generic [question](https://stackoverflow.com/questions/51030769/skstorereviewcontroller-not-showing-app-icon-in-development) to StackOverflow.)

**Comment by magrinj** [comment]
Hello,

Sorry for the delay, I try to take a look, but I think normally you should got the icon of your app if you actually set it. Take a look in the icons of your app, and verify that all the icons are set correctly with all the sizes, let me know if the problem is persisting or not.

**Comment by drbarto** [comment]
@magrinj I just deployed the app and hid the rating feature with a server-side flag to avoid any user-facing mess-ups... luckily the icon did work in production and I could release the feature to all users :) So I assume this was an Xcode-releated problem; it's not uncommon to have stale app icons when running an app locally. Thanks for checking back!
