### ISSUE TITLE
Submit button inactive

### ISSUE THREAD

**Issue by rohitgoyal** [magrinj/react-native-app-store-review#2]
Hi
Once I have selected the rating i want to give the app there appears two buttons 'cancel' and 'submit'. However the submit button is never an active button irrespective of whatever rating i choose. I can not click the submit button.

**Comment by magrinj** [comment]
Hi @rohitgoyal,

The submit button is only active when your app is in release mode, in development mode the pop-up always appear and the submit button stay gray.
In release mode the pop-up can only appear 3 times in a year.

**Comment by rohitgoyal** [comment]
@magrinj  I just checked it by building in release mode. And still facing the same issue.

**Comment by magrinj** [comment]
Ok, is your app already published on the App Store ?
Dis you use the same bundle ID as your release app ?

**Comment by rohitgoyal** [comment]
1) Yes. It is live on AppStore. 
2) Yes

**Comment by magrinj** [comment]
Ok, it's really strange :/
The buttons submit and cancel are on apple side, I can't affect on it, but by reading all of this:

https://developer.apple.com/ios/human-interface-guidelines/interaction/ratings-and-reviews/
https://developer.apple.com/reference/storekit/skstorereviewcontroller/2851536-requestreview?language=objc
http://stackoverflow.com/questions/43073776/skstorereviewcontroller-not-working

Apparently the button will not be grey when your app is published and not just in release mode :)
