### ISSUE TITLE
No Android code in the project?

### ISSUE THREAD

**Issue by ghost** [magrinj/react-native-app-store-review#3]
Am I missing something? I can't see where it pulls in any code for Android?

**Comment by magrinj** [comment]
At this time android is not supported by this library, if you want to add it, feel free to make PR :) 
I originally built this library to be able to call the new iOS pop-up that allow user to rate the app directly inside of it

**Comment by ghost** [comment]
It was just with the steps for Android I assumed they did something :) I'll remove the Android stuff for now.

**Comment by magrinj** [comment]
Yes I just saw, sorry for the misunderstanding :) I just remove the android part from the readme in master

**Comment by ghost** [comment]
No problem and many thanks for the code and help :) We don't actually need it for Android.
