### ISSUE TITLE
Works in emulator but not on a device?

### ISSUE THREAD

**Issue by ghost** [magrinj/react-native-app-store-review#4]
Not sure where else to ask. I've used this and it's working great through the simulator. However when the app is deployed for testing through TestFlight it won't appear?

The devices are all running iOS 10.3, both an iPhone 6 and iPhone 6S have been tested.

Any thoughts? Here's my function:

    _updateLaunchCount = async () => {
      try {
        const numAppLaunches = await AsyncStorage.getItem(NUMLAUNCHES_STORAGE_KEY)
        const appRatingLaunched = await AsyncStorage.getItem(APPRATINGLAUNCHED_STORAGE_KEY)

        if (appRatingLaunched) {
          deviceLog.log("App already launched");
          return
        }

        let newNumAppLaunches = 0
        deviceLog.log('numAppLaunches', numAppLaunches)
        if (!isNaN(parseInt(numAppLaunches))) {
          newNumAppLaunches = parseInt(numAppLaunches) + 1
        } else {
          newNumAppLaunches = 1
        }

        try {
          await AsyncStorage.setItem(NUMLAUNCHES_STORAGE_KEY, newNumAppLaunches.toString())
          deviceLog.log('newNumAppLaunches set to', newNumAppLaunches)
        } catch (error) {
          deviceLog.log('AsyncStorage setItem error: ' + error.message)
        }
        deviceLog.log('appRatingLaunched initally set to', appRatingLaunched)
        if (newNumAppLaunches >= LAUNCHES_BEFORE_RATING && appRatingLaunched !== "true") {
          try {
            await AsyncStorage.setItem(APPRATINGLAUNCHED_STORAGE_KEY, "true")
            deviceLog.log('hasLaunched set to true')
          } catch (error) {
            deviceLog.log('AsyncStorage setItem error: ' + error.message)
          }
          AppStoreReview.requestReview(APP_STORE_ID)
          deviceLog.log('Review request launched')
        }
      } catch (error) {
        deviceLog.log('AsyncStorage getItem error: ' + error.message)
      }
    }

The logging all works as expected and `'Review request launched'` is printed as expected except the review popup doesn't appear on a device?

**Comment by ghost** [comment]
A quick update to this, it works when connected to a device and run through xcode.

**Comment by magrinj** [comment]
Hello @probedb,

Thanks for the report, as suggested in the Apple documentation just here: https://developer.apple.com/reference/storekit/skstorereviewcontroller/2851536-requestreview#discussion
Request review as no effect when distribute by test flight :)

**Comment by magrinj** [comment]
Hello @probedb,

Thanks for the report, as suggested in the Apple documentation just here: https://developer.apple.com/reference/storekit/skstorereviewcontroller/2851536-requestreview#discussion
Request review as no effect when distribute by test flight :)

**Comment by ghost** [comment]
Thank you :) I must've missed it when searching.
