### ISSUE TITLE
Build fails with "Use of undeclared identifier 'SKStoreReviewController'"

### ISSUE THREAD

**Issue by ihor** [magrinj/react-native-app-store-review#5]
Hey,

I'm getting this error on build:
```RNAppStoreReview.m:67:10: Use of undeclared identifier 'SKStoreReviewController'```

Any idea what could it be? 

Thanks

**Comment by magrinj** [comment]
Strange, on which version of iOS did you try to use it ?

**Comment by ihor** [comment]
Just checked it and it is 10.2. So I'm surprised why it is going to the first if branch. I'm very new to the native iOS stuff, please let me know what I can do to help you.

**Comment by magrinj** [comment]
Ok, can you try to edit `RNAppStoreReview.m` and replace this lines:

``` if (SYSTEM_VERSION_GREATER_THAN_OR_EQUAL_TO(@"10.3")) { ```
by
``` if ([[[UIDevice currentDevice] systemVersion] floatValue] >= 10.3)  ```

and 

``` if (SYSTEM_VERSION_GREATER_THAN_OR_EQUAL_TO(@"8.0")) { ```
by
``` if ([[[UIDevice currentDevice] systemVersion] floatValue] >= 8.0)  ```

**Comment by ihor** [comment]
It didn't help. 

But I noticed that it is a "Semantic Issue". As I understand it comes from static code analysis. So it is not actually executing that if branch, just complaining about undeclared identifier.

<img width="1138" alt="screen shot 2017-06-09 at 15 59 09" src="https://user-images.githubusercontent.com/490943/26978659-9ae5be04-4d2c-11e7-9516-4243b45a6c10.png">

Or maybe I just have to update XCode to have the latest SDK available.

**Comment by magrinj** [comment]
Sorry for the delay, I had a lot of work, I just update the library, try it now and tell me if it's working :)

**Comment by ihor** [comment]
Sorry, I disappeared too. I updated XCode and the problem disappeared. Surprisingly there weren't any problems on devices. So I think you can close this ticket. Hope this thread will save somebody some time :)

**Comment by magrinj** [comment]
Ok, I also update the package, and check the availability of the functions in another way, hope this problem doesn't appear anymore :)
I close the ticket, thanks for the report!
