### ISSUE TITLE
Can the prompt be shown more than one time, if you leave an review? 

### ISSUE THREAD

**Issue by EmilScherdin** [magrinj/react-native-app-store-review#6]

**Comment by magrinj** [comment]
Hello, 

As explain in apple documentation: https://developer.apple.com/documentation/storekit/skstorereviewcontroller/2851536-requestreview#discussion

The prompt appear only 3-4 time a year, so to avoid confusion for your user I suggest you to prompt a custom popup before the real, to know if the user really want to rate your app.
At this time, we don't have any callback from the apple function to know if the user really rate the app or not.

Hope my answer is going to help you :)

I close this issue

**Comment by EmilScherdin** [comment]
@magrinj Okey, thanks 🙏🏼

Great package btw 🚀

**Comment by magrinj** [comment]
@EmilScherdin You're welcome! Thanks 👌🏻
