### ISSUE TITLE
Can you add a successful and failed callback?

### ISSUE THREAD

**Issue by baijunjie** [magrinj/react-native-app-store-review#8]
Great plugins！
But the popup scoring view has network latency, I need to know when it will be displayed, or because it will fail for a silent reason and give the user friendly hints.

**Comment by magrinj** [comment]
Hello, at this time the `requestReview` function doesn't give any feedback from the network latency, so I can't give it back to you in the js side :/
https://developer.apple.com/documentation/storekit/skstorereviewcontroller/2851536-requestreview
